### ISSUE TITLE
negative numbers quoted in output

### ISSUE THREAD

**Issue by remster** [databricks/spark-csv#278] opened 2016-03-01 16:44 UTC
when saving dataframes with "com.databricks.spark.csv" negative numbers are quoted (undesired), but only when they appear in the first column.

lib version:     compile "com.databricks:spark-csv_${scalaVersionMain}:1.3.0"
```
Steps to reproduce:
      SparkBase.sqlContext.sql("SELECT -1 as negative, 1 as positive").write
        .format("com.databricks.spark.csv")
        .option("header", "true")
        .option("quoteMode", "NONE")
        .mode(SaveMode.Overwrite)
        .save(mockGridPath.toString)
      new String(
        Files.readAllBytes(Paths.get(mockGridPath.toString, "part-00000"))
      ) must equalTo("negative,positive\n\"-1\",1\n")

      SparkBase.sqlContext.sql("SELECT 1 as positive, -1 as negative").write
        .format("com.databricks.spark.csv")
        .option("header", "true")
        .option("quoteMode", "NONE")
        .mode(SaveMode.Overwrite)
        .save(mockGridPath.toString)
      new String(
        Files.readAllBytes(Paths.get(mockGridPath.toString, "part-00000"))
      ) must equalTo("positive,negative\n1,-1\n")
```

**Comment by HyukjinKwon** [comment] 2016-03-02 00:46
@remster Would you maybe provide some sample dataset and self-runnable codes (with default Spark libraries)?
I think this might be a little bit confusing how to reproduce the issue..

**Comment by remster** [comment] 2016-03-02 07:00
Hi @HyukjinKwon 

I have provided self-runnable codes with the assumption that you can give it a sqlContext (replace SparkBase.sqlContext) and can verify with specs2:
```must equalTo("positive,negative\n1,-1\n")```
or manually.

Essentially then, this fully reproduces the problem:
```
sqlContext.sql("SELECT -1 as negative, 1 as positive").write
        .format("com.databricks.spark.csv")
        .option("header", "true")
        .option("quoteMode", "NONE")
        .mode(SaveMode.Overwrite)
        .save("./someFolder")
```

**Comment by HyukjinKwon** [comment] 2016-03-02 07:16
@remster Thanks!

**Comment by falaki** [comment] 2016-03-02 07:30
This seems to be a serious issue. Thanks for reporting. Will look into it before we make a new release.

**Comment by remster** [comment] 2016-03-02 07:57
Appreciated!

**Comment by falaki** [comment] 2016-03-03 23:55
This is addressed by https://github.com/databricks/spark-csv/pull/271

**Closed** 2016-03-03 23:56 UTC
