### ISSUE TITLE
Example of usage from spark-shell

### ISSUE THREAD

**Issue by zhaidarbek** [databricks/spark-csv#66] opened 2015-06-01 09:21 UTC
I'm trying to get the exampling working with no luck. Could you provide step by step instructions how to get it running?
1. Run spark shell: spark-1.3.1-bin-hadoop2.6\bin>spark-shell.cmd --packages com.databricks:spark-csv_2.10:1.0.3
2. Add imports: 
import org.apache.spark.sql.SQLContext
import com.databricks.spark.csv._
3. Load csv data:
val sqlContext = new SQLContext(sc)
val cars = sqlContext.csvFile("cars.csv")
and after the call to sqlContext.csvFile("cars.csv"):  ERROR Executor: Exception in task 0.0 in stage 4.0 (TID 4)
java.lang.NullPointerException
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1010)

**Comment by falaki** [comment] 2015-06-01 20:56
@zhaidarbek Would you please provide the full stack trace? Also, are you able to run any spark jobs on your windows machine?

**Comment by JoshRosen** [comment] 2015-09-09 01:58
I'm going to close this issue as "Cannot Reproduce" pending more information from @zhaidarbek.

**Closed by JoshRosen** 2015-09-09 01:58 UTC
Labels: Cannot Reproduce
