### ISSUE TITLE
does this work for the spark 1.4.1 

### ISSUE THREAD

**Issue by merlintang** [databricks/spark-csv#118] opened 2015-08-05 23:04 UTC
I run this code 

subset.write.format("com.databricks.spark.csv").option("delimiter", "~").save(outputname)

where subset is a dataframe 

then, it throws those errors 
Exception in thread "main" java.lang.IncompatibleClassChangeError: class com.databricks.spark.csv.CsvRelation has interface org.apache.spark.sql.sources.TableScan as super class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2585)
	at java.lang.Class.getConstructor0(Class.java:2885)
	at java.lang.Class.newInstance(Class.java:350)
	at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:307)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:144)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:135)

Can you check what is happening here ? I am so appreciate your kind help.

**Comment by falaki** [comment] 2015-08-05 23:26
Would you double check if your Spark JARs and your spark-csv JAR are for the same version of Scala?

**Comment by merlintang** [comment] 2015-08-06 16:09
for the spark, I am using the scala 2.10.4 
for the spark-csv, I am using the sbt file. libraryDependencies += "com.databricks" % "spark-csv_2.10" % "1.1.0" . In order to run it on the cluster, I download the jar file from the http://mvnrepository.com/artifact/com.databricks/spark-csv_2.10/1.1.0, and put this jar as the dependence jar. 
thanks for your quick answering. many thanks.

**Comment by marmbrus** [comment] 2015-08-06 17:43
This actually looks like a Spark version mismatch to me.

**Comment by kapil-rajak** [comment] 2015-08-25 11:46
I see the same issue, using given versions.

**Comment by vherasme** [comment] 2015-08-26 12:29
How do I use this in a pySpark notebook (jupyter for example) ?

**Comment by falaki** [comment] 2015-08-26 18:52
@vherasme start pyspark with ``` --packages``` option and pass spark-csv to it (look at the README on github).

**Comment by vherasme** [comment] 2015-08-27 11:17
In my case I only open the terminal (Ubuntu 14.04) and input this:

**ipython notebook --profile spark**

When the notebook opens I run these lines:

**from pyspark import  SparkContext**
**sc = SparkContext( 'local', 'pyspark')**

After that I start creating RDD's as usual.

**Comment by falaki** [comment] 2015-08-27 18:31
I don't know IPythonNotebook enough to answer this. Would be good to ask this on their lists/forumes. Basically you want IPythonNotebook to pass additional arguments to pyspark when it launches it.

**Comment by JoshRosen** [comment] 2015-08-28 19:01
I am going to close this ticket as "Cannot Reproduce" for now. I tested this out locally with many different combinations of compile-time and runtime Spark versions and was unable to reproduce this bug.

@vherasme, I don't think that this issue is the right thread to be discussing questions about using this library with PySpark, since that is not related to the subject of this discussion. If you'd like to continue discussing using IPython and this library then please open a separate issue that is dedicated to that topic. Thanks!

**Closed by JoshRosen** 2015-08-28 19:01 UTC
Labels: Cannot Reproduce

**Comment by JoshRosen** [comment] 2015-08-28 19:02
@kapil-rajak, @merlintang, if you have additional information that can help me to reproduce / debug this issue, then please re-open and update this issue. It would be helpful if you could double-check the exact Spark versions that you're running with. It would also be helpful to list any configurations where this version _did_ work for you.
