### ISSUE TITLE
Spark 2.0.0 Multiple sources found for cvs

### ISSUE THREAD

**Issue by ray6080** [databricks/spark-csv#373] opened 2016-08-08 09:22 UTC
When using `read().csv("path")`, or `write().csv("path")` in Java, I always encountered _Exception in thread "main" java.lang.RuntimeException: Multiple sources found for cvs.

**Comment by HyukjinKwon** [comment] 2016-08-08 09:31
This will be a duplicate of https://github.com/databricks/spark-csv/issues/367. We should not import this CSV package. This library was ported into Spark 2.0.

**Closed** 2016-10-23 14:46 UTC
